name: Setup Dependencies
description: Sets up all project dependecies as required by workflows.
runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install NPM Packages
      run: npm install
      shell: bash
