name: Prepare Release
description: Creates & uploads release artifacts.
inputs:
  build-artifacts-name:
    description: Name of previously uploaded build artifacts.
    required: false
    default: dist
  release-artifacts-name:
    description: Name of release artifacts to be uploaded.
    required: false
    default: release-artifacts
  flag:
    description: Release flag ('dev').
    required: false
    default: ''
outputs:
  release-tarball:
    description: Release tarball.
    value: ${{ steps.prepare-release.outputs.release-tarball }}
runs:
  using: composite
  steps:
    - name: Fetch Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.build-artifacts-name }}
        path: dist
    - name: Prepare Release
      id: prepare-release
      run: npm run prepare:release -- "${{ inputs.flag }}" && echo "::set-output name=release-tarball::$(cat release-tarball-name.txt)"
      shell: bash
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.release-artifacts-name }}
        path: |
          release-log.txt
          release-tarball-name.txt
          ${{ steps.prepare-release.outputs.release-tarball }}
