name: Publish Package
description: Publishes package tarball to all remote package registries.
inputs:
  npm-auth-token:
    description: NPM Auth Token.
    required: true
    default: ''
  github-auth-token:
    description: GitHub Auth Token.
    required: true
    default: ''
  package-artifacts-name:
    description: Name of previously uploaded package artifacts.
    required: false
    default: package-artifacts
runs:
  using: composite
  steps:
    - name: Fetch Package Artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.package-artifacts-name }}
    - name: Read Package Artifacts
      run: echo "PACKAGE_TARBALL=$(cat package-tarball-name.txt)" >> $GITHUB_ENV
      shell: bash
    - name: Publish Package (NPM)
      uses: ./.github/actions/publish-package/to-registry
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Publish Package (GitHub)
      uses: ./.github/actions/publish-package/to-registry
      with:
        registry-name: GitHub
        registry-url: https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-auth-token }}
    - name: Archive Package Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.package-artifacts-name }}
        path: |
          package-log.txt
          package-tarball-name.txt
          ${{ env.PACKAGE_TARBALL }}
