name: Publish Package
description: Publishes tarball in release artifacts to all remote package registries.
inputs:
  npm-auth-token:
    description: NPM Auth Token.
    required: true
    default: ''
  github-auth-token:
    description: GitHub Auth Token.
    required: true
    default: ''
  release-artifacts-name:
    description: Name of previously uploaded release artifacts.
    required: false
    default: release-artifacts
  tag:
    description: Release tag (ie. 'latest', 'next', etc).
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Fetch Release Artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.release-artifacts-name }}
    - name: Read Release Artifacts
      run: echo "RELEASE_TARBALL=$(cat release-tarball-name.txt)" >> $GITHUB_ENV
      shell: bash
    - name: Publish Package (NPM)
      uses: ./.github/actions/publish-package-to-registry
      with:
        release-tarball: ${{ env.RELEASE_TARBALL }}
        tag: ${{ inputs.tag }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Publish Package (GitHub)
      uses: ./.github/actions/publish-package-to-registry
      with:
        release-tarball: ${{ env.RELEASE_TARBALL }}
        tag: ${{ inputs.tag }}
        registry-name: GitHub
        registry-url: https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-auth-token }}
    - name: Archive Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.release-artifacts-name }}
        path: |
          release-log.txt
          release-tarball-name.txt
          ${{ env.RELEASE_TARBALL }}
