name: Publish Package To Registry
description: Publishes package tarball to remote package registry.
inputs:
  node-version:
    description: NodeJS version.
    required: false
    default: '14'
  registry-name:
    description: Registry name.
    required: false
    default: NPM
  registry-url:
    description: Registry url.
    required: false
    default: https://registry.npmjs.org
  scope:
    description: NPM registry scope.
    required: false
    default: '@agogpixel'
runs:
  using: composite
  steps:
    - name: Setup Dependencies
      uses: ./.github/actions/setup-dependencies
      with:
        node-version: '${{ inputs.node-version }}'
        registry-url: '${{ inputs.registry-url }}'
        scope: '${{ inputs.scope }}'
    - name: Publish Package (${{ inputs.registry-name }})
      run: npm run publish-tarball
      shell: bash
