name: Build & Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
jobs:
  Lint-And-Unit-Test:
    name: Lint & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Lint & Unit Test
        uses: ./.github/actions/lint-and-unit-test
  Build-And-Smoke-Test:
    name: Build & Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Build & Smoke Test
        uses: ./.github/actions/build-and-smoke-test
  Publish-Development:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Publish Development
    runs-on: ubuntu-latest
    needs: [Lint-And-Unit-Test, Build-And-Smoke-Test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Prepare Release
        id: prepare-release
        uses: ./.github/actions/prepare-release
        with:
          flag: dev
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GHP_TOKEN }}'
          automatic_release_tag: next
          prerelease: true
          title: Latest Development
          files: ${{ steps.prepare-release.outputs.release-tarball }}
  Publish-Development-Package:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Publish Development Package
    runs-on: ubuntu-latest
    needs: [Publish-Development]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Package
        uses: ./.github/actions/publish-package
        with:
          npm-auth-token: '${{ secrets.NPM_TOKEN }}'
          github-auth-token: '${{ secrets.GHP_TOKEN }}'
          tag: next
  Publish-Development-Docs:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Publish Development Docs
    runs-on: ubuntu-latest
    needs: [Publish-Development]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Fetch Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy To GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/docs
