name: Pre-Release
on:
  push:
    tags:
      - 'v0.[0-9].[0-9]'
      - 'v0.[0-9].[0-9]-[0-9A-Za-z]*'
      - 'v0.[0-9].[1-9][0-9]+'
      - 'v0.[0-9].[1-9][0-9]+-[0-9A-Za-z]*'
      - 'v0.[1-9][0-9]+.[0-9]'
      - 'v0.[1-9][0-9]+.[0-9]-[0-9A-Za-z]*'
      - 'v0.[1-9][0-9]+.[1-9][0-9]+'
      - 'v0.[1-9][0-9]+.[1-9][0-9]+-[0-9A-Za-z]*'
      - 'v[1-9][0-9]*.[0-9].[0-9]-[0-9A-Za-z]*'
      - 'v[1-9][0-9]*.[0-9].[1-9][0-9]+-[0-9A-Za-z]*'
      - 'v[1-9][0-9]*.[1-9][0-9]+.[0-9]-[0-9A-Za-z]*'
      - 'v[1-9][0-9]*.[1-9][0-9]+.[1-9][0-9]+-[0-9A-Za-z]*'
jobs:
  Pre-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Integration Test
        run: npm run test:dist
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: Create Pre-Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.PAT_TOKEN }}'
          prerelease: true
          files: dist
